name: dell-e-port

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "/mnt/vault2/Photos AND Videos:/usr/src/app/external:ro"
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/vault2/uploads/videos:/data/movies
      - /mnt/vault2/uploads/music:/data/music
      - jellyfin_config:/config
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # 🔥 THE GPU PASSTHROUGH. DO NOT REMOVE THIS.
    restart: unless-stopped

volumes:
  pgdata:
  redis-data:
  jellyfin_config:


